name: template

on:
  workflow_call:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: 'echo "$SSH_KEY" > key'
       shell: bash
       env:
         SSH_KEY: ${{secrets.ACA_DB_USERNAME}}

     - name: nuget-token-replacement
       uses: cschleiden/replace-tokens@v1.1        
       with:
         tokenPrefix: '{{'
         tokenSuffix: '}}'
         files: '["Tailspin.SpaceGame.Web/vars-test.tfvars"]'
       env:
         ACA_DB_USERNAME: ${{ secrets.ACA_DB_USERNAME }}
         ACA_DB_PASSWORD: ${{ secrets.ACA_DB_PASSWORD }}
     - name: upload terraform plan
       uses: actions/upload-artifact@v2
       with:
        name: file
        path: ${{ github.workspace }}/Tailspin.SpaceGame.Web/plan.out

     - name: amp cli login
       run: echo "Hello World"