name: template

on:
  workflow_call:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: 'echo "$SSH_KEY" > key'
       shell: bash
       env:
         SSH_KEY: ${{secrets.ACA_DB_USERNAME}}

     - name: Install Azure cli
       run: |
         sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
         curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
         AZ_REPO=$(lsb_release -cs)
         echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
         sudo apt-get update
         sudo apt-get install azure-cli
         
     - uses: Azure/login@v1
       with:
         creds: '${{ secrets.AZURE_CREDENTIALS }}'
         
     - name: nuget-token-replacement
       uses: cschleiden/replace-tokens@v1.1        
       with:
         tokenPrefix: '{{'
         tokenSuffix: '}}'
         files: '["Tailspin.SpaceGame.Web/vars-test.tfvars"]'

     - name: upload terraform plan
       uses: actions/upload-artifact@v2
       with:
        name: file
        path: ${{ github.workspace }}/Tailspin.SpaceGame.Web/vars-test.tfvars

     - name: amp cli login
       run: echo "Hello World"
