name: template

on:
  workflow_call:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: 'echo "$SSH_KEY" #{ACA_DB_USERNAME}# > key'
       shell: bash
       env:
         SSH_KEY: ""

     - name: upload file
       uses: actions/upload-artifact@v2
       with:
        name: file
        path: ${{ github.workspace }}/Tailspin.SpaceGame.Web/vars-test.tfvars

     - name: amp cli login
       run: echo "Hello World"
