name: Manual workflow

on:
  push:
    branches:
      - main
      - 'release-**'
    paths:
      - "Tailspin.SpaceGame.Web/**"
      - ".github/workflows/manual.yml"
  workflow_dispatch:

jobs:
  greet:
    uses: ./.github/workflows/__template.yml