name: Manual workflow

on:
  pull_request:
    paths:
      - "Tailspin.SpaceGame.Web/**"
      - ".github/workflows/manual.yml"
  push:
    branches:
      - main
      - 'release-**'
    paths:
      - "Tailspin.SpaceGame.Web/**"
      - ".github/workflows/manual.yml"
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.ACA_DB_USERNAME}}

  greet:
    uses: ./.github/workflows/__template.yml
