name: Manual workflow

on:
  pull_request:
    paths:
      - "Tailspin.SpaceGame.Web/**"
      - ".github/workflows/manual.yml"
  push:
    branches:
      - main
      - 'release-**'
    paths:
      - "Tailspin.SpaceGame.Web/**"
      - ".github/workflows/manual.yml"
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: token-replacement
        uses: cschleiden/replace-tokens@v1.1        
        with:
          files: '["**/*.yml"]'
        env:
          ACA_DB_USERNAME: ${{secrets.ACA_DB_USERNAME}}
          
      - run: 'echo "$SSH_KEY" > #{ACA_DB_USERNAME}# key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.ACA_DB_USERNAME}}

  greet:
    uses: ./.github/workflows/__template.yml
