name: Manual workflow

on:
  pull_request:
    paths:
      - "Tailspin.SpaceGame.Web/**"
      - ".github/workflows/manual.yml"

  workflow_dispatch:

jobs:
  greet:
    uses: prashant-gupta23/mslearn-tailspin-spacegame-web/.github/workflows/__template.yml@v1